import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as wjcCore from '@grapecity/wijmo';
import reportWebVitals from './reportWebVitals';
wjcCore.setLicenseKey('localhost,137439412643163#B0IZhsnOiwmbBJye0ICRiwiI34TUyJjd7FWZyEFTGZFOBFGZEV6LwlnaZdHNCNFbzZXW8RFR6QzdycGTxgHZ6wEVHhzcPR4azk7dmNHdGRlbyFER9UEUtZDSzlXZFJ4LOJ7ZupHWk94ayNWeKpFSTl4VuVkS8JDNoBHTCdkb4lUeIdEa9lVSm5UY62mUEp5bxRVWhpGN4lWS9oXcYhlZnNFWyoHNOFGe5d5YzMUW594KyhTSSlDUoxka7dnZDdlMXtyVSdGaBl6MsJDMWRHNndmZ6JXWy2yRPdHdZtUdJBTaKFUcZ9EW6Z5alNjN6VHbrIzd0pEO8VlavdFR6NWNhF7T8Z6Rxg5Sjp5bzlnQ7xmMC9UYoJGS95kYk54coRFZkJzdJZ6KiZ5M0ZnSaNmTRJFayF7SQZFU7AlNFhlR8EHbipXdIlmZ9EHVzhFe8VVUvlkSzhDWwYUZCdUe5lFNGVWU5cEaapHbtplI0IyUiwiIxADMCRzQiojIIJCLyMjN6EjM5IzN0IicfJye#4Xfd5nIJBjMSJiOiMkIsIibvl6cuVGd8VEIgQXZlh6U8VGbGBybtpWaXJiOi8kI1xSfiUTSOFlI0IyQiwiIu3Waz9WZ4hXRgAicldXZpZFdy3GclJFIv5mapdlI0IiTisHL3JyS7gDSiojIDJCLi86bpNnblRHeFBCI73mUpRHb55EIv5mapdlI0IiTisHL3JCNGZDRiojIDJCLi86bpNnblRHeFBCIQFETPBCIv5mapdlI0IiTisHL3JyMDBjQiojIDJCLiUmcvNEIv5mapdlI0IiTisHL3JSV8cTQiojIDJCLi86bpNnblRHeFBCI4JXYoNEbhl6YuFmbpZEIv5mapdlI0IiTis7W0ICZyBlIsICNyYDMzADIwEjNwEjMwIjI0ICdyNkIsICdz3GasF6YvxmI0IyctRkIsIiLj9WSgg6YlRXYpJXQiojIh94QiwiIzYTMzQjNyEDN9MDN7MTMiojIklkIs4XXbpjInxmZiwiIyYXMyAjMiojIyVmdiwSZzxWYmpYIJN')

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
